# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grip < Formula
  desc "Fast project and branch switching for git workspaces"
  homepage "https://github.com/yigitozgumus/grip"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.2.0/grip_0.2.0_darwin_amd64.tar.gz"
      sha256 "3f6bfb0d1571c60dfd01fe74da1674e84de65bf32a12d47b242aa7f423baa77e"

      def install
        bin.install "grip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.2.0/grip_0.2.0_darwin_arm64.tar.gz"
      sha256 "1e7040ae4302fd8d49a65bb3f83a60c3cd41d4f4fb02ca66768f1132f3cea883"

      def install
        bin.install "grip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.2.0/grip_0.2.0_linux_amd64.tar.gz"
      sha256 "50cafbc009d2e9fdde8875829780c20d9ef245a2342552adc373009a7b47b57d"
      def install
        bin.install "grip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.2.0/grip_0.2.0_linux_arm64.tar.gz"
      sha256 "7e792bb96e035aebdb62b7cf440c54bde495f0dbfca2a0a524819f0d5c13be11"
      def install
        bin.install "grip"
      end
    end
  end

  test do
    system "#{bin}/grip", "--help"
  end
end
