# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grip < Formula
  desc "Fast project and branch switching for git workspaces"
  homepage "https://github.com/yigitozgumus/grip"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.5.0/grip_0.5.0_darwin_amd64.tar.gz"
      sha256 "0245064cf2e96729ce444a3b3f4199009ef7afe6c38ad7337f5e70410f0d85da"

      def install
        bin.install "grip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.5.0/grip_0.5.0_darwin_arm64.tar.gz"
      sha256 "15ed0191faef028b58b59aa0c60a0ed683cacecfa77fe8a297202855d643c577"

      def install
        bin.install "grip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.5.0/grip_0.5.0_linux_amd64.tar.gz"
      sha256 "29c8667a5b49a0a93d3cdbcac5be360e617578a87642c4fef41a4e2acd1907fc"
      def install
        bin.install "grip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yigitozgumus/grip/releases/download/v0.5.0/grip_0.5.0_linux_arm64.tar.gz"
      sha256 "cc618712615367be3aa4f5cfc8d666b6c5153c1728e1ff347256aad74667b1ec"
      def install
        bin.install "grip"
      end
    end
  end

  test do
    system "#{bin}/grip", "--help"
  end
end
