# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPublish < Formula
  desc ""
  homepage "https://github.com/yigitozgumus/lazy-publish"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.5/lazydraft_1.0.5_macOS_arm64.tar.gz"
      sha256 "1c111508a61ae776ef3724de435b1265fa21d978fac51d90e236fd083fb5657a"

      def install
        bin.install "lazydraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.5/lazydraft_1.0.5_macOS_x86_64.tar.gz"
      sha256 "63a89d8b11c55432cc93f7f5983d4b07bfef5ecc7ba6e9ecda66b8408b0fe4ea"

      def install
        bin.install "lazydraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.5/lazydraft_1.0.5_Linux_x86_64.tar.gz"
      sha256 "de4381ffebbf71f3d6310d3085e83783b2b2e47ce2c5c94549238feaef454166"

      def install
        bin.install "lazydraft"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
