# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydraft < Formula
  desc "lazydraft helps you manage your markdown blog projects in your obsidian workflow. It can transfer the blog project into your static site of choice."
  homepage "https://github.com/yigitozgumus/lazydraft"
  version "2.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.1.0/lazydraft_2.1.0_macOS_arm64.tar.gz"
      sha256 "476bad866267230cdab16f5da769958a843b2c2431b4b25bd0a29e8dc43bb192"

      def install
        bin.install "lazydraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.1.0/lazydraft_2.1.0_macOS_x86_64.tar.gz"
      sha256 "5af8f272b6ea8ff2a88de21060618a6c466dd35539dafb611e256f77759a4cd3"

      def install
        bin.install "lazydraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.1.0/lazydraft_2.1.0_Linux_x86_64.tar.gz"
      sha256 "52d9ccd107db7a2b0d02528c9ce138e88244222927db7a977d47f818b3755555"

      def install
        bin.install "lazydraft"
      end
    end
  end
end
