# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydraft < Formula
  desc "lazydraft helps you manage your markdown blog projects in your obsidian workflow. It can transfer the blog project into your static site of choice."
  homepage "https://github.com/yigitozgumus/lazydraft"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v1.0.8/lazydraft_1.0.8_macOS_arm64.tar.gz"
      sha256 "93645e1ab0db670af67e56d1ecb95c5ccdd767afd9502a5328c633e035ea7d59"

      def install
        bin.install "lazydraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v1.0.8/lazydraft_1.0.8_macOS_x86_64.tar.gz"
      sha256 "124ca03ac861cf7599a9eff50db9cfef074837896ae1012bf165700a7f96e937"

      def install
        bin.install "lazydraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v1.0.8/lazydraft_1.0.8_Linux_x86_64.tar.gz"
      sha256 "e02275471187166b4cc2bb430c1cc7eaa4ec29dd92b14b8089c0b5fe3cfd36b3"

      def install
        bin.install "lazydraft"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
