# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydraft < Formula
  desc "lazydraft helps you manage your markdown blog projects in your obsidian workflow. It can transfer the blog project into your static site of choice."
  homepage "https://github.com/yigitozgumus/lazydraft"
  version "2.0.3"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.0.3/lazydraft_2.0.3_macOS_arm64.tar.gz"
      sha256 "9cc725c8e10a5c074e60d1bf041af2279ed022cb10ad96fa8db2118c6ace5517"

      def install
        bin.install "lazydraft"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.0.3/lazydraft_2.0.3_macOS_x86_64.tar.gz"
      sha256 "b2b49f234de3830c9683ab56536513744496f0c4b699c9002e0dc028a841ec10"

      def install
        bin.install "lazydraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazydraft/releases/download/v2.0.3/lazydraft_2.0.3_Linux_x86_64.tar.gz"
      sha256 "60ff4226232167d7b2a88910b75715ed7c5ee1cd3f077ae2a7d1c440cb7364c2"

      def install
        bin.install "lazydraft"
      end
    end
  end
end
