# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPublish < Formula
  desc ""
  homepage "https://github.com/yigitozgumus/lazy-publish"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.4/lazy-publish_1.0.4_macOS_x86_64.tar.gz"
      sha256 "1618297246ee300bd0b1118d1661161027543e6d2bb0136bd5116b6b3c379bb4"

      def install
        bin.install "lazy-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.4/lazy-publish_1.0.4_macOS_arm64.tar.gz"
      sha256 "b003f4ed45e16fefb5772695fe26d1fe77564380ef0168102462e31b40e1233b"

      def install
        bin.install "lazy-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.4/lazy-publish_1.0.4_Linux_x86_64.tar.gz"
      sha256 "0018ecd06f5d42c48d02188870afd7292987185f10d5decf995955c70eb31ea0"

      def install
        bin.install "lazy-publish"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
